#!/usr/bin/env python3
"""Turns the built browser application into a header the firmware serves.

Every file is stored gzipped, because that is how it goes out: the browser
asks for it that way and the flash holds a third as much. Run after
`npm run build` in ../../Web. The build runs it itself, into the build
directory; there is no need to run it by hand.

Usage: bake-web.py <dist directory> <output header>

Both are required. It used to default to `web_files.h` in the current
directory, and one run by hand from here left a copy beside http_server.c —
where `#include "web_files.h"` finds it before the build directory's. The
firmware then served that copy, days old, whatever the build baked.
"""
import gzip, pathlib, sys

if len(sys.argv) != 3:
    sys.exit(__doc__)
dist = pathlib.Path(sys.argv[1]).resolve()
out = pathlib.Path(sys.argv[2])
if out.resolve().parent == pathlib.Path(__file__).resolve().parent:
    sys.exit('Bake into the build directory, not beside the sources: '
             'http_server.c would include that copy for good.')
if not (dist / 'index.html').exists():
    sys.exit(f'{dist} has no index.html — run `npm run build` in the Web directory first')

files = sorted(p for p in dist.rglob('*') if p.is_file())
lines = ['// Generated by bake-web.py from the built browser application.',
         '// Do not edit: the build regenerates it from Web/dist.',
         '#pragma once', '', '#include <stdint.h>', '#include "http_request.h"', '']
table, total_raw, total_gz = [], 0, 0
for index, path in enumerate(files):
    name = '/' + str(path.relative_to(dist))
    raw = path.read_bytes()
    # mtime 0 so the same input always bakes to the same bytes
    body = gzip.compress(raw, compresslevel=9, mtime=0)
    total_raw += len(raw); total_gz += len(body)
    lines.append(f'// {name}  {len(raw)} bytes, {len(body)} gzipped')
    lines.append(f'static const uint8_t web_file_{index}[] = {{')
    for at in range(0, len(body), 16):
        lines.append('    ' + ''.join(f'0x{b:02x},' for b in body[at:at + 16]))
    lines.append('};')
    table.append((name, index, len(body)))

lines += ['', '// web_file_t is declared in http_request.h, with the code that searches it.',
          'static const web_file_t web_files[] = {']
for name, index, length in table:
    lines.append(f'    {{ "{name}", web_file_{index}, {length} }},')
lines += ['};', '',
          f'#define WEB_FILE_COUNT {len(table)}', '']
out.write_text('\n'.join(lines))
print(f'{out}: {len(table)} files, {total_raw} bytes -> {total_gz} gzipped')
